apiVersion: v1
kind: Pod
metadata:
  name: paper-summary
  namespace: workspace-<your-name-here>
spec:
  containers:
  - name: python
    image: python:3.11-slim
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: paper-summary-storage
      mountPath: /mnt/data  # mount point inside container
  restartPolicy: Never
